# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Cinus
subtitle: 
description: "Life is complex: it has both real and imaginary parts." 
author: Cinus
language: default
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://Cinus.me
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: true

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
sitemap:
        path: sitemap.xml
theme: yilia

social:
        GitHub: https://github.com/ChenXiyu
        Twitter: https://twitter.com/CinusXy
        Facebook: https://www.facebook.com/xiyu.chen.31
        ZhiHu: http://www.zhihu.com/people/chen-xi-yu-43
        Gmail: mailto:xyCinus@gmail.com
# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: git@github.com:ChenXiyu/ChenXiyu.github.io.git
  branch: master
  message: 
- type: git
  repo: git@gitcafe.com:ChenXiyu/Chenxiyu.git
  branck: master
  message:

feed:
        type: atom
        path: atom.xml
        limit: 20

since: 2015
# title
links_title: Links
# links
links:
        Divergery: http://divergery.blog.51cto.com/
        MyGithubPage: http://chenxiyu.github.io/
        依云's Blog: http://lilydjwg.is-programmer.com/
        紫凯茗檬: http://wangkai.club/
        Linux Toy: https://linuxtoy.org/
        Cool Shell: http://cooshell.cn/
        Vimer: http://www.vimer.cn/
        Tyrant's Arch Linux: http://arch.acgtyrant.com/

#duoshuo_shortname: cinus
google_analytics: UA-65939202-1
#tinysou_key: 7a283dc50ad106c80c17
#swiftype_key: Zu6QuaTAujSrBDxSrgqV
#jiathis: true
google_site_verification: pRNsBW4T_Lr63DaKgR7HTLKswgClgTax5YfZ5kAVxzY
disqus_shortname: Chenxiyu
